{% set name = "ccx2paraview" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ccx2paraview-{{ version }}.tar.gz
  sha256: 304738b12effca3ac43ed7cc5852567eb69ae09116ff454d87a762e288e140f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - ccx2paraview = ccx2paraview.ccx2paraview:main

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10

test:
  imports:
    - ccx2paraview
  commands:
    - pip check
  requires:
    - pip

about:
  summary: CalculiX to Paraview converter (frd to vtk/vtu)
  home: https://github.com/calculix/ccx2paraview
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kbrindley
    - jan-janssen
